backend:
  name: git-gateway
  branch: master # o main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

# Colecciones vacías (debería cargar el panel en blanco)
collections: []
